# Generated by Django 6.0.4 on 2026-05-05 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monitoring_interval", models.PositiveIntegerField(default=60)),
                (
                    "alert_threshold_high",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "alert_threshold_low",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
            ],
        ),
    ]
