# Generated by Django 6.0.4 on 2026-05-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_alert_stockprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("stock_us", "Ação EUA"),
                    ("stock_br", "Ação Brasil"),
                    ("fii", "Fundo Imobiliário"),
                ],
                default="stock_us",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="alert_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="stock",
            name="symbol",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
