# Generated by Django 6.0.4 on 2026-05-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monitor",
            "0003_alert_email_sent_stock_tipo_usersettings_alert_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("stock_us", "Ação EUA"),
                    ("stock_br", "Ação Brasil"),
                    ("fii", "Fundo Imobiliário"),
                    ("crypto", "Criptomoeda"),
                ],
                default="stock_us",
                max_length=10,
            ),
        ),
    ]
