# Generated by Django 6.0.4 on 2026-05-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0004_alter_stock_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="alert_threshold_high",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="alert_threshold_low",
        ),
        migrations.AddField(
            model_name="stock",
            name="threshold_high",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="stock",
            name="threshold_low",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
