# Generated by Django 6.0.4 on 2026-05-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0005_remove_usersettings_alert_threshold_high_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="alert_email",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="ntfy_topic",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
