# Generated by Django 6.0.4 on 2026-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0006_remove_usersettings_alert_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="email_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="smtp_host",
            field=models.CharField(default="smtp.gmail.com", max_length=200),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="smtp_password",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="smtp_port",
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="smtp_user",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
